#!/usr/bin/env python3
"""Génère ad_frameworks_db.json — base de données frameworks NoviaAI."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "frameworks" / "ad_frameworks_db.json"

NOVIA = {
    "product": "NoviaAI",
    "value_props": [
        "Appel manqué → texto automatique en ~8 secondes",
        "Agent IA qui qualifie le prospect par SMS",
        "Dashboard : inbox, stats, RDV bookés",
        "Essai gratuit 14 jours · ~199$/mois",
    ],
    "brand_colors": {"navy": "#13325b", "lime": "#c8f135"},
    "cta_url": "noviaai.ca/signup?utm_source={platform}&utm_campaign={niche}-{framework}",
}

SCENE_TYPES = {
    "hook_busy_missed_call": {"asset": "runway", "label": "Entrepreneur occupé, appel entrant"},
    "hook_stat_shock": {"asset": "stat", "label": "Statistique choc plein écran"},
    "hook_pattern_interrupt": {"asset": "runway", "label": "Pattern interrupt visuel"},
    "problem_missed_calls": {"asset": "runway", "label": "Appels manqués, notifications"},
    "problem_client_leaves": {"asset": "runway", "label": "Client part chez concurrent"},
    "problem_revenue_loss": {"asset": "runway", "label": "Perte revenus visualisée"},
    "problem_common_mistake": {"asset": "runway", "label": "Erreur commune du métier"},
    "agitate_urgency": {"asset": "runway", "label": "Montage stressant rapide"},
    "before_chaos": {"asset": "runway", "label": "État avant — chaos"},
    "after_calm": {"asset": "runway", "label": "État après — sérénité"},
    "comparison_without": {"asset": "runway", "label": "Split sans NoviaAI"},
    "comparison_with": {"asset": "runway", "label": "Split avec NoviaAI"},
    "day_in_life_moment": {"asset": "runway", "label": "Moment journée type PME"},
    "solution_sms_mockup": {"asset": "sms_mockup", "label": "Conversation SMS NoviaAI"},
    "solution_dashboard": {"asset": "dashboard", "label": "Dashboard NoviaAI mobile"},
    "proof_rdv_confirmed": {"asset": "runway", "label": "Notification RDV confirmé"},
    "proof_social_stat": {"asset": "stat", "label": "Chiffres résultats"},
    "objection_answer": {"asset": "runway", "label": "Réponse à objection"},
    "offer_stack": {"asset": "stat", "label": "Stack offre (essai+démo+ garantie)"},
    "cta_demo": {"asset": "cta", "label": "Slide CTA final"},
}

EMOTIONS = [
    "frustration", "anxiété", "FOMO", "identification", "soulagement",
    "aspiration", "confiance", "urgence", "curiosité", "sérénité", "désir",
]


def scene(
    num: int,
    start: float,
    end: float,
    role: str,
    scene_type: str,
    description: str,
    emotion: str,
    proof_type: str | None,
    texte: str,
    voix: str,
    visual: str = "",
) -> dict:
    st = SCENE_TYPES.get(scene_type, {"asset": "runway", "label": scene_type})
    return {
        "number": num,
        "timing": f"{int(start)}-{int(end)}s",
        "duration_s": end - start,
        "role": role,
        "scene_type": scene_type,
        "asset": st["asset"],
        "description": description,
        "emotion": emotion,
        "proof_type": proof_type,
        "texte_ecran_template": texte,
        "voix_off_template": voix,
        "visual_brief": visual or description,
    }


def fw(
    id: str,
    name: str,
    psycho: str,
    target: dict,
    hook: dict,
    scenes: list,
    proof: str,
    cta: dict,
    novia: str,
    when_use: list,
    when_not: list,
    tags: list,
    origin: str = "",
    aliases: list | None = None,
) -> dict:
    return {
        "id": id,
        "name": name,
        "aliases": aliases or [],
        "origin": origin,
        "psychological_objective": psycho,
        "target_client": target,
        "hook_3s": hook,
        "scene_count": len(scenes),
        "total_duration_s": 30,
        "scenes": scenes,
        "proof_strategy": proof,
        "cta": cta,
        "noviaai_adaptation": novia,
        "when_to_use": when_use,
        "when_not_to_use": when_not,
        "tags": tags,
    }


TARGET_URGENT = {
    "profile": "Propriétaire-opérateur PME services, 35-55 ans, seul ou 2-5 employés",
    "industries": ["plombier", "électricien", "dépannage", "CVC"],
    "awareness_level": "problem_aware",
    "traffic_temperature": ["cold", "warm"],
    "pain_points": ["appels manqués en job", "urgences perdues", "pas de réceptionniste"],
}

TARGET_ASPIRATION = {
    "profile": "Propriétaire PME rendez-vous, 30-50 ans, agenda à optimiser",
    "industries": ["salon", "clinique", "esthétique", "garage"],
    "awareness_level": "solution_aware",
    "traffic_temperature": ["cold", "warm"],
    "pain_points": ["clientes perdues", "horaire troué", "réponse trop lente"],
}

TARGET_RETARGET = {
    "profile": "Visiteur noviaai.ca ou engagé sans conversion, 40-60 ans",
    "industries": ["toutes PME services"],
    "awareness_level": "product_aware",
    "traffic_temperature": ["retargeting", "warm"],
    "pain_points": ["sceptique IA", "peur complexité", "prix"],
}

CTA_DEMO = {
    "primary": "Demandez votre démonstration gratuite",
    "secondary": "Essai 14 jours sans engagement",
    "url_template": NOVIA["cta_url"],
    "urgency_level": "soft",
}

CTA_TRIAL = {
    "primary": "Commencez votre essai gratuit — 14 jours",
    "secondary": "Aucune carte requise pour la démo",
    "url_template": NOVIA["cta_url"],
    "urgency_level": "medium",
}

CTA_OFFER = {
    "primary": "Réservez votre démo + essai 14 jours",
    "secondary": "Offre fondateur PME Québec — places limitées",
    "url_template": NOVIA["cta_url"],
    "urgency_level": "high",
}

HOOK_EX = {
    "plombier": "Combien de fuites urgentes avez-vous perdues parce que vous étiez sous l'évier?",
    "garage": "Combien de clients ont raccroché pendant que vous étiez sous le capot?",
    "salon": "Combien de clientes avez-vous perdues pendant une coloration?",
}

FRAMEWORKS = [
    fw(
        "pas_classic",
        "Problème → Agitation → Solution",
        "Amplifier la douleur existante (appel manqué) jusqu'à ce que NoviaAI devienne la seule sortie logique et urgente.",
        TARGET_URGENT,
        {
            "type": "question_pain",
            "description": "Question directe sur une perte concrète vécue aujourd'hui",
            "template_fr": "{hook_question}",
            "visual": "Gros plan téléphone qui vibre, mains occupées (outils, gants)",
            "examples_by_niche": HOOK_EX,
        },
        [
            scene(1, 0, 3, "hook", "hook_busy_missed_call",
                  "Plombier/artisan en plein travail. Téléphone vibre. Impossible de décrocher. Regard frustré.",
                  "frustration", None, "{hook_question}", "{hook_voix}"),
            scene(2, 3, 10, "problem", "problem_missed_calls",
                  "Montage : appels manqués, messages non lus, client dans sa voiture qui raccroche.",
                  "anxiété", "empathie_visuelle",
                  "Un appel manqué = un client perdu.",
                  "Chaque jour des clients vous appellent. Personne ne répond assez vite."),
            scene(3, 10, 18, "solution", "solution_sms_mockup",
                  "Transition vers iPhone : conversation SMS NoviaAI — qualification + proposition RDV.",
                  "soulagement", "demo_produit_sms",
                  "Votre assistant IA disponible 24/7.",
                  "NoviaAI répond en 8 secondes, qualifie et propose un rendez-vous."),
            scene(4, 18, 26, "proof", "proof_rdv_confirmed",
                  "Retour terrain : même entrepreneur, notification « RDV confirmé demain 8h », sourire léger.",
                  "sérénité", "resultat_notification",
                  "Nouveau rendez-vous confirmé.",
                  "Pendant que vous travaillez, votre entreprise continue de répondre."),
            scene(5, 26, 30, "cta", "cta_demo",
                  "Slide navy/lime : logo NoviaAI, CTA démo, URL.",
                  "désir", None,
                  "Demandez votre démonstration.\nEssai 14 jours.",
                  "Découvrez NoviaAI — essai gratuit quatorze jours."),
        ],
        "Preuve produit = mockup SMS réel (pas animation générique). Preuve résultat = notification RDV.",
        CTA_DEMO,
        "Ne jamais expliquer l'IA en jargon. Montrer : appel manqué → texto 8 sec → RDV. Scènes 1-2 douleur, 3 produit, 4 résultat.",
        ["Cold traffic Meta/TikTok", "Première pub campagne", "Niches urgence"],
        ["Retargeting chaud", "Audience déjà convaincue"],
        ["cold", "conversion", "default", "pas"],
        "Eugene Schwartz · Direct response · Agences SaaS performance",
        ["PAS", "Problem Agitate Solution"],
    ),
    fw(
        "bab_avant_apres",
        "Avant / Après",
        "Créer un contraste émotionnel fort entre le chaos (sans système) et la sérénité (avec NoviaAI). Le produit est le pont.",
        TARGET_ASPIRATION,
        {
            "type": "before_after_tease",
            "description": "Annoncer visuellement le contraste en 3 secondes",
            "template_fr": "Votre journée {avant_apres} NoviaAI",
            "visual": "Split screen ou texte bold « AVANT » sur scène chaotique",
            "examples_by_niche": {
                "plombier": "Même plombier — deux journées différentes.",
                "garage": "Garage débordé vs garage avec agenda plein.",
                "salon": "Samedi sans NoviaAI vs samedi serein.",
            },
        },
        [
            scene(1, 0, 4, "before", "before_chaos",
                  "Journée sans NoviaAI : téléphone qui sonne en boucle, appels manqués, stress visible.",
                  "anxiété", "empathie_visuelle",
                  "AVANT : votre journée sans NoviaAI.",
                  "Avant : le téléphone sonne, vous perdez des clients, vous stressiez."),
            scene(2, 4, 12, "after_tease", "after_calm",
                  "Même métier, même personne — calme, travaille, notification positive en arrière-plan.",
                  "aspiration", "contraste_visuel",
                  "APRÈS : votre journée avec NoviaAI.",
                  "Après : vous travaillez, NoviaAI répond à votre place."),
            scene(3, 12, 22, "bridge", "solution_sms_mockup",
                  "Le pont : mockup SMS complet montrant qualification automatique.",
                  "curiosité", "demo_produit_sms",
                  "Le pont : texto en 8 sec + RDV auto.",
                  "NoviaAI envoie le texto, qualifie et confirme le rendez-vous."),
            scene(4, 22, 26, "proof", "proof_social_stat",
                  "Stat animée : +N RDV cette semaine.",
                  "confiance", "stat_resultat",
                  "+{n} RDV cette semaine",
                  "Résultats concrets dès la première semaine."),
            scene(5, 26, 30, "cta", "cta_demo",
                  "CTA : passez de l'avant à l'après.",
                  "désir", None,
                  "Passez à l'après.\nDémo gratuite.",
                  "Demandez votre démo — essai quatorze jours."),
        ],
        "Contraste visuel même personnage/métier. Mockup SMS = pont tangible entre les deux états.",
        CTA_DEMO,
        "Utiliser le MÊME acteur visuel (même uniforme, même lieu) pour avant/après. Couleurs plus froides avant, chaudes après.",
        ["Salons, garages, cliniques", "PME débordées pas en crise", "Message aspiration"],
        ["Urgence extrême minuit — préférer PAS"],
        ["bab", "transformation", "aspiration"],
        "StoryBrand · GoHighLevel onboarding",
        ["BAB", "Before After Bridge"],
    ),
    fw(
        "customer_story",
        "Histoire client",
        "Créer identification via micro-récit d'un client fictif crédible (Marc, Julie) — le spectateur se projette.",
        TARGET_URGENT,
        {
            "type": "pattern_interrupt",
            "description": "Affirmation provocante qui reframes le téléphone comme coût",
            "template_fr": "Votre téléphone vous coûte de l'argent.",
            "visual": "Téléphone sur comptoir qui vibre — overlay rouge « $$$ perdu »",
            "examples_by_niche": {
                "plombier": "Votre téléphone vous coûte des urgences à 500$.",
                "garage": "Un client avec un bruit de frein. Parti en 30 secondes.",
                "salon": "Julie voulait une coupe samedi. Elle a appelé ailleurs.",
            },
        },
        [
            scene(1, 0, 3, "hook", "hook_pattern_interrupt",
                  "Pattern interrupt : le téléphone = perte d'argent, pas outil business.",
                  "curiosité", None,
                  "Votre téléphone vous coûte de l'argent.",
                  "Votre téléphone vous coûte de l'argent."),
            scene(2, 3, 12, "story", "problem_client_leaves",
                  "Micro-histoire : « Marc » appelle 3 fois, pas de réponse, Google le concurrent, part.",
                  "identification", "recit_emotionnel",
                  "{prenom} a appelé. Personne n'a répondu.",
                  "{prenom} avait une urgence. Il a appelé trois fois. Puis il est allé chez votre concurrent."),
            scene(3, 12, 22, "offer_setup", "solution_sms_mockup",
                  "Retournement : et si quelqu'un avait répondu? Demo SMS NoviaAI.",
                  "soulagement", "demo_produit_sms",
                  "Et si quelqu'un répondait à votre place?",
                  "NoviaAI répond en huit secondes, pose les bonnes questions et book le RDV."),
            scene(4, 22, 26, "resolution", "proof_rdv_confirmed",
                  "Dénouement : « Marc » aurait booké demain 8h. Propriétaire toujours en job.",
                  "sérénité", "resultat_notification",
                  "{prenom} booké demain 8h.",
                  "{prenom} aurait reçu une confirmation. Vous, vous étiez en job."),
            scene(5, 26, 30, "cta", "cta_demo",
                  "CTA démo + essai.",
                  "désir", None,
                  "Offre : démo gratuite + 14 jours.",
                  "Demandez votre démonstration gratuite."),
        ],
        "Personnifier le CLIENT final (Marc/Julie), jamais le propriétaire NoviaAI. Histoire = 9 secondes max avant demo produit.",
        CTA_DEMO,
        "Prénoms québécois crédibles. Adapter {prenom} : Marc (plombier/garage), Julie (salon). Pas de témoignage fake avec nom d'entreprise.",
        ["Evergreen ads", "Storytelling sans face cam", "Cold/warm mix"],
        ["Besoin preuve immédiate — préférer stat shock"],
        ["story", "hso", "evergreen"],
        "Alex Hormozi Hook-Story-Offer · Adapté SaaS GHL",
        ["HSO", "Hook Story Offer"],
    ),
    fw(
        "product_demo",
        "Démonstration produit",
        "Montrer le produit en action dès les premières secondes — la preuve visuelle vend mieux que l'argument.",
        TARGET_RETARGET,
        {
            "type": "stat_shock",
            "description": "Chiffre de performance produit comme scroll-stop",
            "template_fr": "Réponse en 8 secondes. Automatique.",
            "visual": "Stat « 8 sec » lime sur fond navy + aperçu SMS en transparence",
            "examples_by_niche": {
                "plombier": "Regardez ce qui se passe quand un plombier manque un appel.",
                "garage": "8 secondes — c'est ce que NoviaAI met pour répondre.",
                "salon": "Voici ce que vos clientes reçoivent en 8 secondes.",
            },
        },
        [
            scene(1, 0, 3, "hook", "hook_stat_shock",
                  "Stat produit : « 8 sec » temps de réponse automatique.",
                  "curiosité", "stat_produit",
                  "Réponse en 8 secondes.\nAutomatique.",
                  "Huit secondes. C'est le temps de réponse de NoviaAI."),
            scene(2, 3, 7, "context", "hook_busy_missed_call",
                  "Contexte rapide : entrepreneur occupé, appel manqué.",
                  "identification", "empathie_visuelle",
                  "Pendant que t'es en job…",
                  "Pendant que vous êtes occupé, le client attend."),
            scene(3, 7, 15, "demo", "solution_sms_mockup",
                  "Demo SMS plein écran : conversation qualification complète.",
                  "confiance", "demo_produit_sms",
                  "Texto automatique + qualification IA",
                  "NoviaAI envoie un texto et qualifie le client automatiquement."),
            scene(4, 15, 24, "demo", "solution_dashboard",
                  "Demo dashboard : inbox, RDV, stats appels rattrapés.",
                  "confiance", "demo_produit_dashboard",
                  "Ton dashboard NoviaAI en direct",
                  "Tous vos leads et rendez-vous au même endroit."),
            scene(5, 24, 30, "cta", "cta_demo",
                  "CTA essai.",
                  "désir", None,
                  "Essai gratuit 14 jours\nnoviaai.ca",
                  "Commencez votre essai gratuit aujourd'hui."),
        ],
        "60% demo produit (SMS + dashboard). Utiliser captures Playwright réelles, pas mockups génériques.",
        CTA_TRIAL,
        "Framework idéal pour pub_plombier_GHL. Prioriser assets Playwright existants. Runway minimal (scène 2 seulement).",
        ["Retargeting", "Visiteurs site", "Audience solution-aware", "Reels product-led"],
        ["Cold total sans contexte problème"],
        ["demo", "ghl", "product_led"],
        "GoHighLevel · Product-led growth SaaS",
        ["Product Demo", "Show Don't Tell"],
    ),
    fw(
        "common_mistake",
        "Erreur commune",
        "Nommer une croyance ou habitude fausse du métier, créer un « aha moment », puis proposer la bonne pratique (NoviaAI).",
        TARGET_URGENT,
        {
            "type": "pattern_interrupt",
            "description": "Accuser une erreur que 90% du métier commet",
            "template_fr": "Erreur #1 des {metier}s : laisser sonner sans réponse.",
            "visual": "Texte bold rouge « ERREUR » + téléphone qui sonne ignoré",
            "examples_by_niche": {
                "plombier": "Erreur #1 des plombiers : rappeler seulement le soir.",
                "garage": "Erreur #1 des garages : laisser la boîte vocale faire le travail.",
                "salon": "Erreur #1 des salons : demander aux clientes de rappeler.",
            },
        },
        [
            scene(1, 0, 3, "hook", "hook_pattern_interrupt",
                  "Accroche « Erreur #1 » — scroll stop par correction imminente.",
                  "curiosité", None,
                  "Erreur #1 : laisser sonner sans réponse.",
                  "La plus grosse erreur? Laisser sonner sans répondre."),
            scene(2, 3, 10, "mistake", "problem_common_mistake",
                  "Montrer l'erreur : boîte vocale, rappel tardif, post-it « rappeler ».",
                  "identification", "eduction_probleme",
                  "60% ne laissent jamais de message.",
                  "Soixante pour cent de vos clients ne laissent jamais de message vocal."),
            scene(3, 10, 18, "correction", "solution_sms_mockup",
                  "La bonne pratique : texto automatique immédiat post-appel manqué.",
                  "soulagement", "demo_produit_sms",
                  "La solution : texto en 8 sec, pas rappel le soir.",
                  "NoviaAI envoie un texto en huit secondes — pas demain, maintenant."),
            scene(4, 18, 26, "proof", "proof_rdv_confirmed",
                  "Résultat : client rattrapé, RDV booké.",
                  "confiance", "resultat_notification",
                  "Client rattrapé. RDV confirmé.",
                  "Le client est rattrapé avant même d'appeler votre concurrent."),
            scene(5, 26, 30, "cta", "cta_demo",
                  "CTA corriger l'erreur.",
                  "urgence", None,
                  "Corrigez l'erreur #1.\nDémo gratuite.",
                  "Arrêtez de perdre des clients — demandez votre démo."),
        ],
        "Ton « conseil entre pairs », pas condescendant. Erreur = comportement, pas insulte.",
        CTA_DEMO,
        "Erreurs par niche : plombier = rappeler le soir; garage = boîte vocale; salon = « rappelez-nous ». Toujours lier à appel manqué.",
        ["Cold traffic éducatif", "Contenu valeur Meta", "Niches traditionnelles"],
        ["Audience déjà convertie"],
        ["education", "mistake", "cold"],
        "Agences contenu B2B · « Mistake ads » Meta",
        ["Mistake Ad", "Erreur fatale"],
    ),
    fw(
        "transformation",
        "Transformation",
        "Arc émotionnel complet : qui j'étais → ce qui a changé → qui je suis devenu. Plus personnel que Avant/Après.",
        TARGET_ASPIRATION,
        {
            "type": "relatable_moment",
            "description": "Moment vécu universel du propriétaire débordé",
            "template_fr": "Il y a 6 mois, je perdais 3 clients par semaine.",
            "visual": "Close-up mains fatiguées, téléphone avec 5 appels manqués",
            "examples_by_niche": {
                "plombier": "Avant : je finissais mes jobs à minuit… et je rappelais personne.",
                "garage": "Avant : mon agenda avait des trous que je ne comblais jamais.",
                "salon": "Avant : je perdais des clientes chaque samedi.",
            },
        },
        [
            scene(1, 0, 4, "before_self", "before_chaos",
                  "Voix-off « il y a 6 mois » — chaos, culpabilité, clients perdus.",
                  "frustration", "recit_emotionnel",
                  "Avant : clients perdus chaque semaine.",
                  "Il y a six mois, je perdais trois clients par semaine."),
            scene(2, 4, 10, "turning_point", "hook_pattern_interrupt",
                  "Point tournant : découverte qu'on peut automatiser la réponse.",
                  "curiosité", "education",
                  "Puis j'ai découvert NoviaAI.",
                  "Puis j'ai découvert qu'on pouvait répondre automatiquement."),
            scene(3, 10, 20, "transformation", "solution_sms_mockup",
                  "Montage transformation : SMS demo + dashboard + RDV qui s'accumulent.",
                  "aspiration", "demo_produit_sms",
                  "Maintenant : réponse 24/7, RDV auto.",
                  "Maintenant NoviaAI répond vingt-quatre heures sur sept et book mes rendez-vous."),
            scene(4, 20, 26, "after_self", "after_calm",
                  "État transformé : serein, focus métier, stats positives.",
                  "sérénité", "stat_resultat",
                  "Résultat : +{n} RDV/mois, zéro stress.",
                  "Plus douze rendez-vous par mois. Et je dors tranquille."),
            scene(5, 26, 30, "cta", "cta_demo",
                  "Invitation même transformation.",
                  "désir", None,
                  "Votre transformation commence ici.\nEssai 14 jours.",
                  "Votre transformation commence ici — essai gratuit."),
        ],
        "Voix-off première personne du propriétaire PME (pas fondateur NoviaAI). Visuel = acteur métier.",
        CTA_TRIAL,
        "Ne pas confondre avec témoignage client réel — c'est un arc narratif composite. OK pour pub tant que pas de faux nom d'entreprise.",
        ["Salons, garages", "Message inspiration", "Lookalike clients existants"],
        ["Cold sans contexte"],
        ["transformation", "arc", "aspiration"],
        "Hero's Journey simplifié · SaaS onboarding",
        ["Transformation Arc"],
    ),
    fw(
        "comparison",
        "Comparaison",
        "Contraste explicite SANS NoviaAI vs AVEC NoviaAI — clarifier la décision binaire.",
        TARGET_URGENT,
        {
            "type": "before_after_tease",
            "description": "Split ou alternance rapide deux réalités",
            "template_fr": "Sans NoviaAI vs Avec NoviaAI — la différence?",
            "visual": "Split screen vertical : gauche rouge/gris, droite lime/navy",
            "examples_by_niche": {
                "plombier": "Sans NoviaAI : appel manqué. Avec NoviaAI : texto en 8 sec.",
                "garage": "Option A : boîte vocale. Option B : RDV booké automatiquement.",
                "salon": "Sans : cliente perdue. Avec : créneau confirmé par SMS.",
            },
        },
        [
            scene(1, 0, 3, "hook", "hook_pattern_interrupt",
                  "Annonce comparaison directe.",
                  "curiosité", None,
                  "Sans NoviaAI vs Avec NoviaAI",
                  "Quelle est la différence entre répondre et ne pas répondre?"),
            scene(2, 3, 10, "without", "comparison_without",
                  "Colonne SANS : appel manqué → client part → calendrier vide → stress.",
                  "anxiété", "contraste_visuel",
                  "SANS : appel manqué → client perdu.",
                  "Sans NoviaAI : l'appel est manqué, le client appelle ailleurs."),
            scene(3, 10, 18, "with", "comparison_with",
                  "Colonne AVEC : appel manqué → texto 8 sec → qualification → RDV.",
                  "soulagement", "demo_produit_sms",
                  "AVEC : texto 8 sec → RDV confirmé.",
                  "Avec NoviaAI : texto en huit secondes, client qualifié, RDV booké."),
            scene(4, 18, 26, "side_by_side", "proof_social_stat",
                  "Tableau comparatif animé : temps réponse, RDV/semaine, stress.",
                  "confiance", "stat_comparative",
                  "8 sec vs jamais · +{n} RDV vs 0",
                  "Huit secondes contre jamais. Plus douze RDV contre zéro."),
            scene(5, 26, 30, "cta", "cta_demo",
                  "CTA choisir le bon côté.",
                  "désir", None,
                  "Choisissez « Avec ».\nDémo gratuite.",
                  "Choisissez la version avec NoviaAI — démo gratuite."),
        ],
        "Split screen ou alternance cuts rapides. Gauche = rouge/gris, droite = lime/navy brand.",
        CTA_DEMO,
        "Comparaison factuelle, pas dénigrer concurrents. Comparer « sans système » vs « avec NoviaAI », pas vs autre SaaS.",
        ["Décideurs rationnels", "Retargeting", "A/B vs PAS"],
        ["Storytelling pur"],
        ["comparison", "split", "rational"],
        "SaaS comparison pages · Meta side-by-side ads",
        ["Versus", "A vs B"],
    ),
    fw(
        "day_in_life",
        "Journée dans la vie du client",
        "Suivre une journée type du propriétaire PME — moments où NoviaAI intervient naturellement.",
        TARGET_ASPIRATION,
        {
            "type": "relatable_moment",
            "description": "Réveil / première job de la journée — immersion immédiate",
            "template_fr": "6h du matin. Premier appel de la journée.",
            "visual": "Aube, camionnette, café, téléphone déjà actif",
            "examples_by_niche": {
                "plombier": "7h : première urgence. 11h : sous l'évier. 15h : NoviaAI book demain.",
                "garage": "8h : ouverture garage. 12h : sous le capot. 16h : 2 RDV confirmés par SMS.",
                "salon": "9h : première cliente. 14h : coloration. 17h : 3 RDV bookés sans décrocher.",
            },
        },
        [
            scene(1, 0, 3, "hook", "day_in_life_moment",
                  "Ouverture journée : réveil, premier appel ou notification.",
                  "identification", "empathie_visuelle",
                  "6h du matin. Premier appel.",
                  "Six heures du matin. Premier appel de la journée."),
            scene(2, 3, 9, "morning", "hook_busy_missed_call",
                  "Matinée : en job, appel manqué #1.",
                  "frustration", "empathie_visuelle",
                  "En job — impossible de répondre.",
                  "En plein travail, impossible de décrocher."),
            scene(3, 9, 17, "midday", "solution_sms_mockup",
                  "Midi : NoviaAI a répondu, conversation SMS visible.",
                  "soulagement", "demo_produit_sms",
                  "NoviaAI répond pendant que vous travaillez.",
                  "Pendant que vous travaillez, NoviaAI répond et qualifie."),
            scene(4, 17, 26, "afternoon", "proof_rdv_confirmed",
                  "Après-midi : notifications RDV, fin de journée sereine.",
                  "sérénité", "resultat_notification",
                  "Fin de journée : 3 RDV confirmés.",
                  "Fin de journée : trois rendez-vous confirmés sans stress."),
            scene(5, 26, 30, "cta", "cta_demo",
                  "CTA.",
                  "désir", None,
                  "Simplifiez votre journée.\nEssai 14 jours.",
                  "Simplifiez votre journée — essai gratuit."),
        ],
        "Narration temporelle (matin → soir). NoviaAI = personnage invisible qui travaille en arrière-plan.",
        CTA_TRIAL,
        "3 moments clés suffisent (pas documentaire 30s). Horodatages en texte écran renforcent le réalisme.",
        ["Salons, garages", "Contenu immersion", "Warm traffic"],
        ["Cold scroll rapide"],
        ["day_in_life", "immersion", "narrative"],
        "Brand documentary style · ServiceTitan",
        ["Day in the Life", "DITL"],
    ),
    fw(
        "objection_response",
        "Objection → Réponse",
        "Nommer l'objection en premier, y répondre avec preuve produit — idéal retargeting.",
        TARGET_RETARGET,
        {
            "type": "pattern_interrupt",
            "description": "Citation directe de l'objection en guillemets",
            "template_fr": "« {objection} »",
            "visual": "Texte objection en gros + entrepreneur qui hoche la tête",
            "examples_by_niche": {
                "plombier": "« J'ai pas le temps de gérer un robot. »",
                "garage": "« L'IA va dire n'importe quoi à mes clients. »",
                "salon": "« Mes clientes veulent parler à une vraie personne. »",
            },
        },
        [
            scene(1, 0, 4, "objection", "objection_answer",
                  "Objection affichée texte écran + voix-off la cite.",
                  "identification", "objection_nommee",
                  "« {objection} »",
                  "Vous pensez : {objection}"),
            scene(2, 4, 10, "response", "objection_answer",
                  "Réponse directe : NoviaAI ne demande pas plus de temps.",
                  "soulagement", "argument_reponse",
                  "NoviaAI travaille PENDANT que vous travaillez.",
                  "NoviaAI ne demande pas plus de temps. Il répond quand vous ne pouvez pas."),
            scene(3, 10, 18, "proof", "solution_sms_mockup",
                  "Preuve : mockup SMS montrant qualité réponses.",
                  "confiance", "demo_produit_sms",
                  "Réponse pro en 8 sec — vous gardez le contrôle.",
                  "Le client reçoit un texto professionnel. Vous recevez le résumé."),
            scene(4, 18, 26, "proof2", "proof_social_stat",
                  "Preuve ROI : 199$/mois, 1 client = rentabilisé.",
                  "confiance", "stat_roi",
                  "199$/mois · 1 client = rentabilisé",
                  "Cent quatre-vingt-dix-neuf dollars. Un client rattrapé et c'est payé."),
            scene(5, 26, 30, "cta", "cta_demo",
                  "CTA risque zéro.",
                  "désir", None,
                  "Essai 14 jours — zéro engagement.",
                  "Essai gratuit quatorze jours. Annulez quand vous voulez."),
        ],
        "Objection en guillemets dès scène 1. Réponse = preuve visuelle, pas slide texte.",
        CTA_TRIAL,
        "Objections par niche documentées. Essai 14j = réduction risque. Ne pas inventer témoignage.",
        ["Retargeting noviaai.ca", "Audience 35-55 sceptique", "3+ impressions sans conversion"],
        ["Cold traffic — objections prématurées"],
        ["objection", "retargeting"],
        "SaaS retargeting · GHL webinar funnels",
        ["Objection Crusher"],
    ),
    fw(
        "irresistible_offer",
        "Offre irrésistible",
        "Stack valeur (essai + démo + setup + garantie) — créer urgence douce sans fausse rareté.",
        TARGET_RETARGET,
        {
            "type": "social_proof_open",
            "description": "Lead avec la valeur totale de l'offre",
            "template_fr": "Essai 14 jours + démo personnalisée + setup gratuit",
            "visual": "Stack cards animées lime sur navy — checklist qui se coche",
            "examples_by_niche": {
                "plombier": "Offre PME services : tout inclus pour les plombiers du Québec.",
                "garage": "14 jours gratuits + agent configuré pour votre garage.",
                "salon": "Essai salon : RDV auto configuré en 24h.",
            },
        },
        [
            scene(1, 0, 3, "hook", "offer_stack",
                  "Stack offre animé : 3-4 éléments valeur.",
                  "curiosité", "offre_stack",
                  "Essai 14j + Démo + Setup\nValeur 500$ — Gratuit",
                  "Essai quatorze jours, démo personnalisée et configuration — gratuit."),
            scene(2, 3, 8, "problem", "problem_missed_calls",
                  "Rappel rapide du problème (3 sec problem + 2 sec agitate).",
                  "FOMO", "empathie_visuelle",
                  "Chaque appel manqué = argent perdu.",
                  "Chaque appel manqué, c'est de l'argent qui s'en va."),
            scene(3, 8, 18, "value", "solution_sms_mockup",
                  "Ce qu'ils obtiennent : demo SMS + agent qualifié.",
                  "désir", "demo_produit_sms",
                  "Inclus : agent IA + SMS auto + dashboard",
                  "Vous obtenez un agent IA, des textos automatiques et un dashboard complet."),
            scene(4, 18, 26, "guarantee", "proof_social_stat",
                  "Garantie : annulez quand vous voulez, 1 client = ROI.",
                  "confiance", "stat_roi",
                  "Annulez quand vous voulez · ROI en 1 client",
                  "Annulez quand vous voulez. Un client rattrapé et c'est rentabilisé."),
            scene(5, 26, 30, "cta", "cta_demo",
                  "CTA urgence douce.",
                  "urgence", None,
                  "Réservez votre démo\nPlaces limitées ce mois",
                  "Réservez votre démo — places limitées ce mois-ci."),
        ],
        "Stack 3-4 éléments max. « Places limitées » = onboarding capacity réelle, pas fake scarcity.",
        CTA_OFFER,
        "Offre = essai 14j + démo 30min + setup niche (plombier/garage/salon). Valeur ancrée ~500$ (setup + 2 semaines).",
        ["Retargeting chaud", "Fin de funnel", "Promo lancement Québec"],
        ["Cold sans connaissance produit"],
        ["offer", "stack", "conversion"],
        "Hormozi Value Equation · SaaS trial offers",
        ["Irresistible Offer", "Value Stack"],
    ),
    fw(
        "lost_revenue",
        "Revenus perdus (ROI)",
        "Quantifier la perte en dollars — activer le cerveau rationnel du propriétaire PME.",
        {**TARGET_URGENT, "awareness_level": "problem_aware", "traffic_temperature": ["warm", "retargeting"]},
        {
            "type": "stat_shock",
            "description": "Montant dollar par appel manqué",
            "template_fr": "1 appel manqué = {montant}$ perdus",
            "visual": "Compteur dollar animé rouge → lime",
            "examples_by_niche": {
                "plombier": "1 urgence manquée = 500$ dans le vide.",
                "garage": "1 freinage perdu = 350$.",
                "salon": "1 coloration perdue = 120$.",
            },
        },
        [
            scene(1, 0, 4, "hook", "hook_stat_shock",
                  "Chiffre dollar par transaction perdue.",
                  "anxiété", "stat_financiere",
                  "1 appel manqué = {montant}$",
                  "Un seul appel manqué peut vous coûter {montant} dollars."),
            scene(2, 4, 11, "agitate", "problem_revenue_loss",
                  "Multiplication : ×3/semaine = X$/mois.",
                  "anxiété", "stat_financiere",
                  "× 3/semaine = {montant_mois}$/mois",
                  "Multipliez par trois par semaine. Des milliers par mois."),
            scene(3, 11, 20, "solution", "solution_sms_mockup",
                  "NoviaAI rattrape avant que le client parte.",
                  "soulagement", "demo_produit_sms",
                  "NoviaAI rattrape en 8 sec",
                  "NoviaAI transforme l'appel manqué en rendez-vous."),
            scene(4, 20, 26, "roi", "proof_social_stat",
                  "ROI : 1 client = abonnement payé (199$/mois).",
                  "confiance", "stat_roi",
                  "1 client rattrapé = forfait payé",
                  "Un client rattrapé paie votre abonnement."),
            scene(5, 26, 30, "cta", "cta_demo",
                  "CTA calculer ses pertes.",
                  "désir", None,
                  "Calculez vos pertes.\nDémo gratuite.",
                  "Demandez une démo et voyez combien vous perdez."),
        ],
        "Montants par niche : plombier 500$, garage 350$, salon 120$. Ancrage forfait 199$/mois.",
        CTA_DEMO,
        "Adapter {montant} et {montant_mois} via NICHE_DEFAULTS. Toujours relier ROI à 1 client = rentabilisé.",
        ["Décideurs ROI", "Retargeting post-pub émotionnelle", "Garage/plombier commercial"],
        ["Première impression cold — trop froid"],
        ["roi", "rational", "finance"],
        "HubSpot · ServiceTitan · Agences comptables PME",
        ["Lost Revenue", "ROI Calculator"],
    ),
    fw(
        "social_proof",
        "Preuve sociale",
        "Ouvrir avec un résultat concret d'un pair — réduire le risque perçu avant de montrer le produit.",
        {**TARGET_ASPIRATION, "awareness_level": "solution_aware"},
        {
            "type": "social_proof_open",
            "description": "Résultat chiffré d'abord",
            "template_fr": "+{n} RDV bookés en 7 jours",
            "visual": "Stat lime plein écran + badge « PME Québec »",
            "examples_by_niche": {
                "plombier": "+12 urgences bookées en 7 jours.",
                "garage": "+8 RDV qualifiés cette semaine.",
                "salon": "+15 nouvelles clientes ce mois.",
            },
        },
        [
            scene(1, 0, 4, "hook", "proof_social_stat",
                  "Résultat chiffré scroll-stop.",
                  "confiance", "stat_resultat",
                  "+{n} RDV en 7 jours",
                  "Plus {n} rendez-vous bookés en une semaine."),
            scene(2, 4, 10, "context", "hook_busy_missed_call",
                  "Un {metier} comme vous — même problème.",
                  "identification", "empathie_visuelle",
                  "Un {metier} comme vous",
                  "Un {metier} comme vous — trop d'appels manqués."),
            scene(3, 10, 18, "how", "solution_sms_mockup",
                  "Comment : demo SMS.",
                  "curiosité", "demo_produit_sms",
                  "Voici comment ça marche",
                  "NoviaAI envoie un texto en huit secondes et qualifie."),
            scene(4, 18, 26, "proof", "proof_rdv_confirmed",
                  "Résultat final serein.",
                  "sérénité", "resultat_notification",
                  "RDV confirmés sans décrocher",
                  "Rendez-vous confirmés sans décrocher."),
            scene(5, 26, 30, "cta", "cta_demo",
                  "CTA rejoindre.",
                  "désir", None,
                  "Rejoignez les PME qui convertissent.",
                  "Demandez votre démo — essai quatorze jours."),
        ],
        "Stats réelles dashboard si dispo. Sinon fourchette conservative (+3 à +15). Jamais nom entreprise sans consentement.",
        CTA_DEMO,
        "Anonymiser : « un plombier à Laval » pas « Plomberie X ». Utiliser stats agrégées NoviaAI quand possible.",
        ["Scaling Meta", "Lookalike", "Phase preuve"],
        ["Sans chiffres crédibles"],
        ["proof", "social", "scaling"],
        "Intercom case studies · Jobber ads",
        ["Social Proof", "Case Study Micro"],
    ),
]

DB = {
    "schema_version": "1.0.0",
    "product": NOVIA,
    "scene_types": SCENE_TYPES,
    "emotions": EMOTIONS,
    "proof_types": {
        "demo_produit_sms": "Mockup SMS Playwright — conversation qualification réelle",
        "demo_produit_dashboard": "Capture dashboard mobile Playwright",
        "stat_resultat": "Stat animée MoviePy (+N RDV, 8 sec)",
        "stat_financiere": "Chiffre dollar animé",
        "stat_roi": "Comparaison prix forfait vs 1 client gagné",
        "stat_produit": "Métrique produit (8 sec réponse)",
        "stat_comparative": "Tableau sans vs avec",
        "resultat_notification": "Push notification RDV confirmé",
        "empathie_visuelle": "B-roll métier reconnaissable",
        "recit_emotionnel": "Micro-histoire client fictif",
        "objection_nommee": "Citation objection en guillemets",
        "argument_reponse": "Réponse visuelle à objection",
        "offre_stack": "Stack valeur animé",
        "contraste_visuel": "Avant/après ou split screen",
        "education": "Contenu éducatif métier",
    },
    "niche_defaults": {
        "plombier": {"metier": "plombier", "montant": "500", "montant_mois": "6000", "n": "12", "stat": "60", "prenom": "Marc", "objection": "J'ai pas le temps de gérer un robot"},
        "garage": {"metier": "garage", "montant": "350", "montant_mois": "4200", "n": "8", "stat": "60", "prenom": "Marc", "objection": "L'IA va dire n'importe quoi à mes clients"},
        "salon": {"metier": "salon", "montant": "120", "montant_mois": "1920", "n": "15", "stat": "50", "prenom": "Julie", "objection": "Mes clientes veulent parler à une vraie personne"},
        "electricien": {"metier": "électricien", "montant": "400", "montant_mois": "4800", "n": "10", "stat": "60", "prenom": "Marc", "objection": "Je suis jamais au bureau pour configurer ça"},
    },
    "recommendation_matrix": {
        "cold_urgent": "pas_classic",
        "cold_distracted": "product_demo",
        "cold_educational": "common_mistake",
        "aspiration": "bab_avant_apres",
        "story_evergreen": "customer_story",
        "retargeting": "objection_response",
        "roi_focus": "lost_revenue",
        "has_client_stats": "social_proof",
        "comparison_decision": "comparison",
        "immersion": "day_in_life",
        "transformation_arc": "transformation",
        "offer_close": "irresistible_offer",
    },
    "framework_count": len(FRAMEWORKS),
    "frameworks": {f["id"]: f for f in FRAMEWORKS},
}


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(DB, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Base de donnees : {OUT}")
    print(f"Frameworks : {DB['framework_count']}")


if __name__ == "__main__":
    main()
